import { createEffect, createSignal } from "solid-js";
import context from "./context";

const comp2 = (ctx) => {
  const { data, ok, bool } = ctx;
  console.log(ctx);
  const [num, setNum] = createSignal(0);

  return function Comp2(props) {
    setNum((x) => ++x);
    return (
      <div>
        <p>
          Once Comp1 delivered it, the context should say: ok is{" "}
          {ok ? "true" : "false"}{" "}
        </p>
        <p>
          This component received the bool via Context:{" "}
          {bool() ? "true" : "false"}
        </p>
        <p>
          {" "}
          The data generated by Component 1 should be available soon: {data} --
        </p>
        <p>Each time the component is called, the count increases: {num()}</p>
        {props?.children}
      </div>
    );
  };
};

export default comp2(context);
